examples/contact-browser/.gitignore
examples/contact-browser/Makefile
examples/contact-browser/README.markdown
examples/contact-browser/css/app.css
examples/contact-browser/css/spinner.css
examples/contact-browser/index.html
examples/contact-browser/package.json
examples/contact-browser/scripts/embedder.js
examples/contact-browser/src/app.jsx
pdc/apps/changeset/serializers.py
pdc/apps/changeset/tests.py
pdc/apps/component/filters.py
pdc/apps/component/migrations/0004_auto_20150708_0746.py
pdc/apps/component/models.py
pdc/apps/component/serializers.py
pdc/apps/component/tests.py
pdc/apps/component/views.py
pdc/apps/compose/tests.py
pdc/apps/compose/views.py
pdc/apps/package/views.py
pdc/pdc-sync-ldap

These are most changes from the last two weeks.

Sync for sprint 22

---

pdc/apps/contact/serializers.py
pdc/apps/contact/tests.py
pdc/apps/contact/views.py

Refactor resource url field to id in contact app

---

pdc/apps/repository/tests.py
pdc/apps/repository/views.py

Define error message when clone repo.

---

pdc/apps/component/filters.py
pdc/apps/component/fixtures/tests/release_component_for_relationship.json
pdc/apps/component/fixtures/tests/release_component_relationship.json
pdc/apps/component/migrations/0005_auto_20150727_0929.py
pdc/apps/component/models.py
pdc/apps/component/serializers.py
pdc/apps/component/tests.py
pdc/apps/component/views.py
pdc/routers.py

Support create, edit and query relationships between
release components.
JIRA: PDC-816

Support relationship for release components

---

CONTRIBUTING.markdown

This has instructions on how to fix review comments and guidelines for
merging pull requests with preserving nice history.

Add CONTRIBUTING guide

---

pdc/apps/package/models.py
pdc/apps/package/serializers.py
pdc/apps/package/views.py

* document `compose` filter
* display a list of composes for each image
PDC-712

Improve compose images

---

.travis.yml

This pull request tries to speed up the builds on Travis by caching installed dependencies. Not tested yet, please do not merge.

Enable cache on Travis

---

pdc/apps/compose/fixtures/tests/image-manifest.json
pdc/apps/compose/lib.py
pdc/apps/compose/models.py
pdc/apps/compose/tests.py
pdc/apps/release/lib.py
pdc/apps/release/tests.py

Log basic information about imported releases and composes.

Import logging

---

pdc/apps/compose/lib.py
pdc/apps/compose/views.py
pdc/apps/utils/__init__.py
pdc/apps/utils/messaging.py
pdc/apps/utils/middleware.py
pdc/settings.py
requirements/production.txt

Adds sample config in `settings.py`;
Requires `stomp.py` to be installed.

Add StompMessenger to send msg via STOMP.

---

pdc/settings.py

Change DEFAULT_METADATA_CLASS to contrib.bulk_operations.metadata.BulkMetadata

Fix setting DEFAULT_METADATA_CLASS

---

pdc/apps/compose/tests.py

Overlapping merge requests are not only ugly, they could also cause
test failures. Even though both merges separately passed tests, since
the RPM-to-release linking changed the output of release serializer,
tests added in compose/package refactor were broken.

Fix failing tests

---

README
README.markdown

It would look like [this](https://github.com/release-engineering/product-definition-center/tree/readme-badges).

Add build information to README

---

pdc/apps/auth/views.py
pdc/apps/changeset/views.py
pdc/apps/common/renderers.py
pdc/apps/common/tests.py
pdc/apps/common/views.py
pdc/apps/component/views.py
pdc/apps/compose/views.py
pdc/apps/contact/views.py
pdc/apps/package/views.py
pdc/apps/release/views.py
pdc/apps/repository/views.py

More details are [in the commit message of the first commit](https://github.com/release-engineering/product-definition-center/commit/a67676235390ada6c9f13f932ec9ed1a5d712fe6).

Provide list of filters automatically

---

pdc/apps/common/renderers.py
pdc/apps/compose/serializers.py
pdc/apps/utils/SortedRouter.py
pdc/apps/utils/tests.py
pdc/apps/utils/utils.py

This makes it a little easier to read.

Decode % codes in urls in API root

---

pdc/apps/auth/serializers.py
pdc/apps/auth/views.py
pdc/apps/changeset/views.py
pdc/apps/common/renderers.py
pdc/apps/common/tests.py
pdc/apps/common/views.py
pdc/apps/component/serializers.py
pdc/apps/component/views.py
pdc/apps/compose/serializers.py
pdc/apps/compose/views.py
pdc/apps/contact/views.py
pdc/apps/package/serializers.py
pdc/apps/package/views.py
pdc/apps/release/serializers.py
pdc/apps/release/views.py
pdc/apps/repository/views.py

Please see commit messages on the first two commits to get more details.
There are some code changes in renderer, other than that it is mostly documentation adjustments.

Auto serializer

---

pdc/apps/component/views.py

This patch was merged at about the same time as the automatic serializer
support and it was not used yet.
JIRA: PDC-977

Use automatic serializer for component types

---

pdc/apps/repository/serializers.py
pdc/apps/repository/tests.py
pdc/apps/repository/views.py
pdc/routers.py

And link to them from content-delivery-repos.
JIRA: PDC-917
PDC-918
PDC-919

Create read-only list of services, content formats, content categories.

---

pdc/apps/release/templates/release_detail.html

This patch adds total count of repos, displays their primary ids
(useful for API manipulation).
It also enables sorting and filtering of the table.
JIRA: PDC-978

Improve web view of repos

---

pdc/apps/release/views.py

Fix a typo in release types API doc

---

pdc/apps/release/views.py

Fix another typo in release type doc

---

pdc/apps/compose/lib.py
pdc/apps/compose/tests.py

When images or rpms are imported and compose id in composeinfo and
rpm/image manifest is not the same, report an error. This could happen
when user picks manifest for different compose by mistake.
It does not do any sophisticated validations nor does it compare any
other fields.
JIRA: PDC-952

Report error when importing inconsistent data

---

pdc/apps/changeset/filters.py
pdc/apps/changeset/fixtures/tests/changeset.json
pdc/apps/changeset/middleware.py
pdc/apps/changeset/migrations/0003_changeset_pdc_change_comment.py
pdc/apps/changeset/models.py
pdc/apps/changeset/serializers.py
pdc/apps/changeset/templates/changeset_detail.html
pdc/apps/changeset/tests.py
pdc/apps/changeset/views.py
pdc/apps/common/renderers.py
pdc_client/__init__.py
pdc_client/bin/pdc_client

As a user I want to keep track of reasons for changes
JIRA: PDC-923

Keep track of reasons for changes.

---

pdc/apps/common/filters.py
pdc/apps/component/filters.py
pdc/apps/package/filters.py
pdc/apps/package/tests.py

Make bootable filter on images case-insensitive
JIRA: PDC-947

PDC-947,the boolean values for filters should not be case sensitive

---

pdc/apps/compose/views.py
pdc/apps/repository/views.py

This series of patches only fixes links in documentation.

Documentation fixes

---

pdc/apps/compose/tests.py
pdc/apps/contact/tests.py
pdc/apps/repository/tests.py
pdc/settings.py
pdc/settings_test.py

Change non_field_errors to detail.

---

pdc/apps/common/renderers.py
pdc/apps/package/serializers.py

Fix displayed value of RPM filename default

---

pdc/apps/changeset/fixtures/tests/changeset.json
pdc/apps/changeset/middleware.py
pdc/apps/changeset/migrations/0004_changeset_requested_on.py
pdc/apps/changeset/migrations/0005_changeset_requested_on_data_migration.py
pdc/apps/changeset/migrations/0006_auto_20150914_0308.py
pdc/apps/changeset/models.py
pdc/apps/changeset/serializers.py
pdc/apps/changeset/templates/changeset_detail.html
pdc/apps/changeset/templates/changeset_list.html
pdc/apps/changeset/views.py

Track request duration in changesets.

---

pdc/apps/common/filters.py
pdc/apps/package/tests.py

The filter displayed name of filter as the database filter, not what
user specified.
JIRA: PDC-999

Fix error message in strict int filter

---

pdc_client/__init__.py
pdc_client/bin/pdc
pdc_client/plugins.py
pdc_client/plugins/image.py
pdc_client/plugins/release.py
pdc_client/plugins/rpm.py

Implement base support for user friendly client with plugins for releases and rpms.

Client rebased

---

docs/source/development.rst

The project can run with the docker container
and this commit share the steps in document.
JIRA: PDC-950

Update the setup document

---

pdc_client/plugin_helpers.py
pdc_client/tests/tests.py

Also add a lot of comments to explain what is going on. There is an
assertion to verify the result has the correct form.
A simple test is added to make sure it works.

Fix extract_arguments to allow nested dictionaries

---

pdc/apps/utils/templatetags/pdctags.py
pdc/settings.py
pdc/templates/base_generic.html

Load LOGIN_URL from settings and use that. Kerberos auth is no longer
hardcoded, but it is still the default settings value.

Make login URL customizable

---

pdc/apps/common/renderers.py
pdc/apps/component/migrations/0004_auto_20150708_0746.py
pdc/apps/component/migrations/0009_releasecomponenttype_has_osbs.py
pdc/apps/component/models.py
pdc/apps/component/serializers.py
pdc/apps/osbs/__init__.py
pdc/apps/osbs/admin.py
pdc/apps/osbs/apps.py
pdc/apps/osbs/filters.py
pdc/apps/osbs/fixtures/tests/records.json
pdc/apps/osbs/migrations/0001_initial.py
pdc/apps/osbs/models.py
pdc/apps/osbs/serializers.py
pdc/apps/osbs/signals.py
pdc/apps/osbs/tests.py
pdc/apps/osbs/views.py
pdc/routers.py
pdc/settings.py

Currently `autorebuild` only. Please see commit message on the second commit for more details.

Add tracking OSBS metadata

---

.travis.yml
Makefile
pdc/apps/osbs/migrations/0002_auto_20151001_1115.py
verify-migrations.sh

This is run with make all_tests as well as on Travis-CI.

Add script to verify migrations are up to date

---

pdc_client/plugins/component.py

Correct the `bugzilla_component` output format.

FIX: release component info format.

---

pdc/apps/repository/views.py

This action was added when repos got identifiers. It was not
documented, though.
PDC-1071

Add documentation to repo retrieve

---

pdc/apps/release/serializers.py
pdc/apps/release/tests.py
pdc_client/plugins/release.py
pdc_client/test_helpers.py
pdc_client/tests/component/tests.py
pdc_client/tests/compose/tests.py
pdc_client/tests/release/tests.py

First commit contains a fix for release api.

Fix client release update

---

pdc/apps/package/serializers.py

The input should be a list of strings, not a single string.
JIRA: PDC-1029

Fix dependency documentation

---

pdc/templates/base_generic.html

When user is logged in, the changes are accessible through this link.
JIRA: PDC-1052

Add link to change list to user menu

---

pdc/apps/repository/filters.py

The value should be an integer.
JIRA: PDC-1104

Fix product_id filter on content delivery repos

---

pdc/apps/component/views.py

Make /update fields consistent with /create and new client arguments.

Update docs in GlobalComponent views.

---

examples/find-duplicated-contacts.py

While this script is not terribly useful for day-to-day life, it can
serve as an example on how to use the client.
JIRA: PDC-1105

Add example script to find components with duplicate contacts

---

pdc/apps/compose/templates/compose_list.html
pdc/apps/compose/templates/overrides_form.html
pdc/apps/release/templates/base_product_list.html
pdc/apps/release/templates/product_list.html
pdc/apps/release/templates/product_version_list.html
pdc/apps/release/templates/release_list.html
pdc/apps/utils/templatetags/pdctags.py
pdc/static/pdc/style.css
pdc/templates/help_button.html
pdc/templates/help_modal.html

Each list page on the UI now has a help button. Clicking this button
displays a popup with description what the page represents.
JIRA: PDC-714

Add description to web ui

---

pdc/apps/osbs/views.py

Add description to osbs end-point

---

pdc_client/bin/pdc_client

Fix debug output of pdc_client

---

pdc/menu.py

Move the base-product link from Releases menu to Products menu
JIRA: PDC-1091

 Restructure the menu UI

---

docs/source/using_api.rst
pdc/apps/changeset/views.py

The purpose of the changeset API is not obvious and there were no hints about it in the API doc.

Improve documentation

---

pdc_client/plugins/release.py
pdc_client/tests/release/tests.py

Add 'clone' action to release client command.

---

pdc_client/plugins/component.py
pdc_client/tests/component/data/global_component/detail.json
pdc_client/tests/component/data/global_component/detail.txt
pdc_client/tests/component/data/release_component/detail.json
pdc_client/tests/component/data/release_component/detail.txt
pdc_client/tests/component/tests.py

Will ignore old contacts if any.
JIRA: PDC-1166

Update Component client command to use new contact API.

---

pdc/apps/auth/views.py

Fix crash after log out

---

pdc/apps/auth/backends.py
pdc/apps/auth/migrations/0003_auto_20151126_0811.py
pdc/apps/auth/models.py
pdc/apps/auth/templates/user_profile.html
pdc/apps/auth/tests.py
pdc/apps/auth/views.py
pdc/pdc-sync-ldap

User single string instead of first name and last
name combination.
JIRA: PDC-1051

Use single string field for user names.

---

pdc/apps/auth/models.py

Get back the necessary abstract method.

---

pdc/apps/component/serializers.py
pdc/apps/component/tests.py
pdc/apps/component/views.py

Allow update global component for release component.

---

requirements/production.txt

Django version should be >=1.8.1and <1.9

Change required Django version in range [1.8.1, 1.9)

---

pdc/apps/package/migrations/0007_auto_20151208_1011.py
pdc/apps/package/models.py
pdc/apps/package/tests.py

Allow single NVR (image_id) have multiple different formats

---

pdc/apps/compose/models.py
pdc/apps/compose/serializers.py
pdc/apps/compose/views.py

1. Get compose to Sigkeys' key_id mapping wholly instead of
one by one.
2. Use select_related in some places to reduce DB access.
JIRA: PDC-1254

Try to improve composes list performance.

---

pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Raise error when missing some inputs

---

pdc/apps/compose/views.py

Add response info for composes/{compose_id}/rpm-mapping/{package}

---

pdc/apps/component/tests.py
pdc/apps/release/views.py

Info error when clone release component for target release
which with inactive.
JIRA: PDC-1282

Add error info when release component clone with inactive

---

pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Raise error when there are wrong inputs or wrong input format.

---

pdc/apps/compose/tests.py
pdc/apps/package/filters.py
pdc/apps/package/fixtures/test/rpm2.json
pdc/apps/package/migrations/0009_rpm_built_for_release.py
pdc/apps/package/models.py
pdc/apps/package/serializers.py
pdc/apps/package/tests.py

Add optional "built-for-release" field in rpms resource

---

pdc/apps/compose/tests.py
pdc/apps/compose/views.py

When input error Compose or Variant, return error info.
JIRA:PDC-1232

Add error message for compose-tree-locations.

---

pdc/apps/package/models.py
pdc/apps/package/tests.py

Fix the bug when change RPM built_for_release field won't record.

---

pdc/apps/compose/fixtures/tests/image-manifest.json
pdc/apps/package/migrations/0010_auto_20160218_1339.py
pdc/apps/package/models.py

Allow import images work when filed 'implant_md5' is null.

---

pdc/apps/package/migrations/0011_auto_20160219_0915.py

Add 2 image formats 'tar.gz' and 'tar.xz'.
Add 1 image type 'docker'.
JIRA: PDC-1341

Add 2 image formats and 1 image type.

---

pdc/apps/repository/routers.py
pdc/apps/repository/tests.py
pdc/apps/repository/views.py

Fore the content-delivery-repos api, update the endpoint
with /content-delivery-repos/; and update the test case.
JIRA: PDC-1340

Update the content-delivery-repos URL

---

pdc/apps/repository/views.py

Update the documetation in webUI; which API include:content-delivery-repos,
rpc/repos/clone, repo-families, content-delivery-content-category,
content-delivery-content-format/s,content-delivery-service/s.
JIRA: PDC-1339

Update the doc for some API

---

pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Delete method in compose resource will mark
compose as 'deleted'.
Not allow to mark "undelete" in normal (PATCH/PUT) way.
JIRA: PDC-1359

Allow marking composes as deleted

---

pdc/apps/changeset/middleware.py
pdc/apps/compose/lib.py
pdc/apps/compose/routers.py
pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Ability to import compose-rpms, compose-images at once (atomicity).

---

pdc/apps/compose/views.py

Add queryset to pass permissions check to
avoid ;server internal error' in web page footer.
JIRA: PDC-1393

Fix the full compose import API web page footer error.

---

pdc/apps/compose/templates/compose_detail.html

Add special format and text in deleted compose detail page
heading part to indicate this compose is already deleted.
JIRA: PDC-1347

Indicate a compose is deleted in its detail page.

---

pdc/apps/compose/lib.py
pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Add set compose tree location function to compose full import

---

Makefile

Remove the client test in server repo

---

pdc/apps/contact/views.py

Remove useless header informations for some APIs

---

pdc/apps/compose/templates/compose_detail.html

Visible for Arch names on compose page

---

pdc/apps/release/signals.py
pdc/apps/release/views.py

So binding part could customize its behavior accroding
to signals and the data with the signal.
For example, record object data before and after update.
JIRA: PDC-1321

Send signal when product is created or updated.

---

pdc/apps/compose/models.py
pdc/apps/compose/tests.py
pdc/apps/compose/views.py

1. For partial update, 'include' is only for 'action' is 'create'.
2. If 'action' is 'delete', treat include value properly in
model.
3. Check parameters format in PUT method.
JIRA: PDC-1335, PDC-1390

Check compose rpm mapping parameters strictly and fix bug.

---

pdc/apps/compose/templates/compose_detail.html

Stop truncating arch names on compose page

---

pdc/apps/package/models.py

Initial image formats and types from productmd.

---

pdc/apps/auth/models.py

Sorted permission list with the same api name

---

pdc/apps/common/filters.py
pdc/apps/component/tests.py
pdc/apps/compose/filters.py
pdc/apps/compose/tests.py
pdc/apps/package/tests.py
pdc/apps/release/filters.py
pdc/apps/release/tests.py
pdc/apps/repository/filters.py
pdc/apps/repository/tests.py

Return warning when query in boolean field with illegal value.

---

pdc/apps/auth/views.py

Update the view of auth/token api

---

pdc/apps/compose/lib.py

Both for imports of new content.  One for 'images' and the other for 'rpms'.
This is ultimately in pursuit of fixing fedora-infra/pdc-updater#10.

Publish two new message topics.

---

pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Fix the bug about "Manage Overrides" on release without compose

---

pdc/apps/common/constants.py
pdc/apps/component/views.py
pdc/apps/package/views.py
pdc/apps/release/views.py

JIRA: PDC-1456
Only if the field in serializer is explicitly setting default value will make this happen.

Add doc to note the user when PUT optional parameter.

---

pdc/scripts/create_release_components.py

Small refactoring of a function from pdc/scripts/create_release_components.py

Simplify _bulk_insert_resource func in create_release_components.py

---

pdc/apps/common/serializers.py
pdc/apps/common/tests.py

Empty string "" is not unique.
PDC-1456

Set unique Charfield's default value to None insteadof empty string.

---

pdc/apps/repository/views.py

We have remove rhe release type validation in repo validation,
So update the doc in sync.
JIRA:PDC-1481

Update the doc in Repo API

---

pdc/apps/repository/fixtures/tests/multiple_repos.json
pdc/apps/repository/serializers.py
pdc/apps/repository/tests.py

Allow to clone repositories with None product_id

---

pdc/apps/release/serializers.py
pdc/apps/release/tests.py

Make Release.integrated_with accept null as input.

---

pdc/apps/package/migrations/0013_set_default_subvariant_to_empty_string.py
pdc/apps/package/models.py
pdc/apps/package/tests.py

Pass empty string to productmd instead of None.

---

pdc/apps/release/serializers.py

Fix a bug and add a flag for resource permissions.

---

docs/source/deployment.rst

Document how to configure when behind a reverse proxy

---

pdc/apps/auth/templates/user_profile.html
pdc/apps/auth/views.py
pdc/apps/utils/middleware.py
pdc/apps/utils/utils.py

Create UI to display resource permissions in auth profile.

---

pdc/apps/changeset/middleware.py

Fix a url mistake in mail content.

---

pdc/apps/auth/tests.py
pdc/apps/auth/views.py

Fix a bug for api auth/resource-permissions retrieve method.

---

pdc.spec

For resource based permissions.
JIRA: PDC-1501

Add python-django-rest-framework-composed-permissions as a dependency.

---

pdc/apps/compose/fixtures/tests/images-1.2.json
pdc/apps/compose/fixtures/tests/rpms-1.2.json
pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Update documentation for compose rpm mapping's bulk update method.

---

pdc/apps/compose/routers.py
pdc/apps/compose/views.py

Change "ComposeTreeRTTTestVewSet" to "ComposeTreeRTTTestViewSet"

---

pdc/apps/compose/migrations/0011_remove_duplicate_pathtypes.py
pdc/apps/compose/migrations/0012_auto_20160615_0611.py
pdc/apps/compose/models.py

Add unique to Compose PathType's name field.

---

pdc/apps/compose/filters.py
pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Group rpm query parameters in and operation.

---

pdc/apps/compose/lib.py
requirements/devel.txt
requirements/production.txt

1. Define the productmd dependency to specific version.
2. Fix a module error when run script from internal
code base.
JIRA: PDC-1572

Fix sync.sh problem in upstream version part.

---

pdc/apps/compose/tests.py
pdc/apps/compose/views.py

Fix bugs when inputing wrong format which will return server error

---

pdc/apps/utils/tests.py
pdc/settings.py

Add cache control headers to PDC HTTP response

---

pdc/apps/common/viewsets.py
pdc/apps/release/tests.py
pdc/apps/release/views.py

Fix bugs in cache control and add test cases.

---

pdc/apps/common/templates/browsable_api/api.html

Add page switch to the bottom

---

pdc/apps/compose/views.py

Doc change for compose api to mention how compose get created

---

pdc/apps/compose/views.py

API compose-rpms is changed as well.
JIRA: PDC-1600

Add more details to compose-images API docs.

---

pdc/apps/compose/views.py

Change doc description for compose/compose-images/compose-rpms

---

pdc/apps/compose/views.py

Change the wrong doc description.

---

pdc/apps/common/pagination.py
pdc/apps/common/templates/browsable_api/api.html
pdc/apps/common/templates/browsable_api/numbers.html

Make page always locate at page header part.

---

pdc/apps/compose/tests.py
pdc/apps/compose/views.py

For API  /composes/{compose_id}/rpm-mapping/
JIRA: PDC-1613

Support multiple dict values and empty input 

---

docs/source/using_api.rst
pdc/apps/common/viewsets.py
pdc/settings_local.py.dist

The valid fields is included in model fields of all APIs.
JIRA: PDC-1512

Update the valid fields for ordering

---

pdc/apps/common/viewsets.py

Update the error info and looks friendly.

---

pdc/apps/auth/serializers.py
pdc/apps/auth/tests.py

Make group resource permission work correctly in PATCH method

---

pdc/apps/auth/serializers.py
pdc/apps/auth/tests.py

When post or put method violate group-resource-permissions
API uniquenness restriction, give a more friendly
prompt.
JIRA: PDC-1655

Change group-resource-permissions API prompt.

---

pdc/apps/auth/templates/user_profile.html
pdc/static/pdc/style.css

Display 'No' value in table with red color, and 'Yes' value with
green color.
JIRA: PDC-1550

UI for displaying resource permission

---

pdc/apps/release/templates/product_list.html
pdc/apps/release/templates/product_list_include.html
pdc/apps/release/templates/product_version_list.html
pdc/apps/release/templates/product_version_list_include.html
pdc/apps/release/templates/release_list.html
pdc/apps/release/templates/release_list_include.html
pdc/static/js/datatable_active_filter.js
pdc/templates/base_generic.html

For releases, product versions and products APIs; add selector attribute
in datatable, which instead of the Column Name.And click the seletor
to filter and display all/active/inactive status.
JIRA: PDC-1589

Display all/active/inactive 

---

pdc/apps/release/templates/product_list_include.html
pdc/apps/release/templates/product_version_list_include.html
pdc/apps/release/templates/release_list_include.html
pdc/apps/release/views.py

Fix the bug from QE
JIRA:PDC-1589

Display all/active/inactive and filter the datatable

---

pdc/apps/release/templates/product_list_include.html
pdc/apps/release/templates/product_version_list_include.html
pdc/apps/release/templates/release_list_include.html
pdc/apps/release/views.py
pdc/static/js/datatable_active_filter.js

Rename the colunm name for release, product version and product

---

examples/find-duplicated-contacts.py
pdc/apps/auth/templates/api_perms.html
pdc/apps/auth/views.py
pdc/apps/common/renderers.py
pdc/apps/repository/tests.py
pdc/menu.py
pdc/urls.py

The WebUI shows the API permission, which includes all users and groups.
Because 'read' permission is available for all users and groups, instead of the values by @all.
JIRA: PDC-1757

To list all API permissions

---

pdc/apps/auth/templates/api_perms.html
pdc/apps/auth/views.py

To verify the 'read' permission for all members

---

pdc/apps/auth/views.py

To fix the bug when testing PDC-1757

---

pdc/apps/auth/templates/api_perms.html
pdc/apps/auth/views.py

The users will hide and show in their group botton; the superusers_list
include all superusers.
JIRA: PDC-1762

WebUI shows the groups and superusers

---

pdc/apps/compose/views.py
requirements/devel.txt
requirements/production.txt

Default view of composes should be reversed in order

---

pdc/apps/component/filters.py
pdc/apps/component/fixtures/tests/release_component_relationship_type.json
pdc/apps/component/models.py
pdc/apps/component/serializers.py
pdc/apps/component/tests.py
pdc/apps/component/views.py

Allows to add, update and remove items from
"component-relationship-types" list.
Also allows to filter the types by name.
JIRA: PDC-1843

Allow to add/update/remove component relationship types

---

pdc.spec

Add python-django-jsonfield as a dependency

---

pdc/apps/common/renderers.py

Add descending ordering documentation on API pages

---

pdc/apps/release/filters.py
pdc/apps/release/migrations/0010_release_sigkey.py
pdc/apps/release/models.py
pdc/apps/release/serializers.py
pdc/apps/release/tests.py

Add signing key in release api
JIRA: PDC-1984

Add signing key in release api

---

pdc/apps/release/filters.py
pdc/apps/release/fixtures/tests/cpes.json
pdc/apps/release/migrations/0011_auto_20170912_1108.py
pdc/apps/release/models.py
pdc/apps/release/routers.py
pdc/apps/release/serializers.py
pdc/apps/release/tests.py
pdc/apps/release/views.py

This is continuation of #462.
Contains quick fixes for admin page for CPE pointed out by @larry-shi.

CPE improvements

---

pdc/apps/release/filters.py
pdc/apps/release/migrations/0012_release_allow_buildroot_push.py
pdc/apps/release/models.py
pdc/apps/release/serializers.py
pdc/apps/release/tests.py

Add some simple test cases and modify existing cases as well.
JIRA: PDC-1897

Add allow_buildroot_push to release API

---

pdc/apps/release/migrations/0011_auto_20170912_1108.py

JIRA: PDC-2228
---
Migration worked fine with sqlite db in my dev environment. I should start using **postgreSQL database for development** too.

Fix migrating CPE field from string to ID

---

Dockerfile

I had issues getting the Docker environment working with the Fedora 21 image. This upgrades it to use the Fedora 26 image.

Update Dockerfile to use Fedora 26

---

.gitignore
pdc/apps/componentbranch/filters.py
pdc/apps/componentbranch/tests.py

Addresses:
https://pagure.io/releng/issue/6976

Make ComponentBranch API filters case-sensitive

---

pdc/apps/release/filters.py
pdc/apps/release/migrations/0013_release_allowed_debuginfos.py
pdc/apps/release/models.py
pdc/apps/release/serializers.py
pdc/apps/release/tests.py
pdc/apps/repository/models.py

Add allowed_debuginfos for release
JIRA： PDC-1971

Add allowed_debuginfos for release

---

docs/source/development.rst

doc: fix "then" spelling

---

contrib/drf_introspection/__init__.py
contrib/drf_introspection/serializers.py
pdc/apps/common/renderers.py
pdc/apps/common/serializers.py
pdc/apps/common/tests.py
pdc/apps/component/serializers.py
pdc/apps/component/views.py
pdc/apps/componentbranch/serializers.py
pdc/apps/componentbranch/views.py
pdc/apps/compose/serializers.py
pdc/apps/contact/serializers.py
pdc/apps/module/serializers.py
pdc/apps/module/views.py
pdc/apps/package/serializers.py

This can improve performance, e.g. omit additional SQL queries to fetch
data for foreign keys.

Allow to select which fields to display

---

pdc/apps/release/migrations/0015_auto_20171004_0807.py
pdc/apps/release/models.py
pdc/apps/release/tests.py

Disallow removing a CPE used in variant-cpes

---

pdc/apps/release/tests.py
pdc/apps/release/views.py
pdc/apps/repository/tests.py

Update push target tests and API description

---

pdc/apps/release/models.py
pdc/apps/release/serializers.py
pdc/apps/release/tests.py

Fix status code for creating duplicate CPE binding

---

pdc/apps/repository/filters.py
pdc/apps/repository/fixtures/tests/multi_destination.json
pdc/apps/repository/migrations/0004_multidestination.py
pdc/apps/repository/models.py
pdc/apps/repository/routers.py
pdc/apps/repository/serializers.py
pdc/apps/repository/tests.py
pdc/apps/repository/views.py

Add multi-destinations (multi-product) endpoint

---

pdc.spec
requirements/production.txt

Restrict djangorestframework's version to include more error info.

Restrict djangorestframework's version

---

pdc/apps/release/fixtures/tests/variants_standalone.json
pdc/apps/release/serializers.py
pdc/apps/release/tests.py
pdc/apps/repository/tests.py

Fix partial update of variant-cpes

---

contrib/bulk_operations/bulk_operations.py
pdc/apps/auth/serializers.py
pdc/apps/auth/tests.py

Fix reporting some validation errors

---

pdc/apps/common/renderers.py
pdc/apps/repository/filters.py

Fix filter type of IDs in docs

---

pdc/apps/release/filters.py
pdc/apps/release/serializers.py
pdc/apps/release/tests.py
pdc/apps/release/views.py

Use numerical ID to refer to variant-cpes

---

pdc/apps/repository/filters.py
pdc/apps/repository/tests.py

Fix filtering by subscribers for mutli-destinations

---

pdc/apps/repository/filters.py
pdc/apps/repository/tests.py

Allow filter multi-destinations by repo names

---

pdc/apps/repository/models.py

Fix checking arch for multi-destinations API

---

pdc/apps/changeset/middleware.py
pdc/settings_local.py.dist

Omit sending "big data change" e-mails for whitelisted authors

---

pdc/apps/package/views.py

Clarify docs for RPM dependency filtering

---

.gitignore
pdc/apps/auth/models.py
pdc/apps/bindings/models.py
pdc/apps/changeset/models.py
pdc/apps/common/filters.py
pdc/apps/common/viewsets.py
pdc/apps/component/models.py
pdc/apps/component/tests.py
pdc/apps/componentbranch/filters.py
pdc/apps/compose/models.py
pdc/apps/compose/tests.py
pdc/apps/compose/views.py
pdc/apps/contact/models.py
pdc/apps/osbs/models.py
pdc/apps/package/models.py
pdc/apps/release/models.py
pdc/apps/release/serializers.py
pdc/apps/repository/models.py
pdc/apps/usage/models.py
pdc/apps/utils/templatetags/pdctags.py

---
Some changes from [upgrade-django branch](https://github.com/hluk/product-definition-center/tree/upgrade-django) (migration to new Django).
These changes are compatible with Django 1.8 so they can be reviewed and merged now.

Pre upgrade django

---

pdc/apps/release/migrations/0016_auto_20180131_0312.py
pdc/apps/release/models.py
pdc/apps/release/serializers.py
pdc/apps/release/tests.py

Add multi CPEs for one variant
JIRA: PDC-2542

Add multi CPEs for one variant

---

pdc/static/js/datatable_active_filter.js

The default is not guaranteed to be 10.

Include radix in parseInt call

---

pdc/apps/common/renderers.py

Fix "fields" filter documentation

---

pdc/apps/common/renderers.py
pdc/apps/common/tests.py

Single API documentation page is connected to one view class. The class
is instantiated for each request. Caching API pages by view instance not
only breaks caching but also leaks memory (view instances are stored as
keys for broken cache).
---
Hmm, not sure how to write tests for this. Perhaps I could test the decorator `cached_by_argument_class` separately.

Fix cache for filters and serializers

---

contrib/drf_introspection/serializers.py
pdc/apps/common/tests.py
pdc/apps/contact/serializers.py

Raise error on invalid field names in field filters

---

pdc/apps/changeset/filters.py
pdc/apps/changeset/tests.py

Fix changesets filter with timezone aware datetime

---

pdc/apps/package/models.py

JIRA: PDC-2587
---
Doesn't help performance much unfortunately. It's difficult to measure the speed improvements with debug toolbar since it adds some overhead and postgresql server is using some system-wide caching.

List only non-deleted linked_composes

---

pdc/apps/module/filters.py
pdc/apps/module/tests.py

Fix filtering multiple components

---

contrib/drf_introspection/serializers.py
contrib/drf_introspection/tests.py
pdc/apps/common/tests.py

Fix passing fields/exclude_fields as GET arguments

---

pdc/apps/module/filters.py
pdc/apps/module/tests.py

Fix listing distinct modules
