product-definition-center/product-definition-center

- pdc/apps/compose/serializers.py
- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
This pull request adds identifier to override rpms. This allows easier deleting.
Fixes PDC-683 and PDC-885.
> Add id to override rpms

- pdc/apps/repository/tests.py
After docker was added as a content_format, the tests were not passing.
This patch updates the test so that it no longer expects a specific list
of possible values but only verifies that the error message has some
options.
> Fix failing repo test

- .travis.yml
- Makefile
- pdc/settings_test.py
- tox.ini
After every pull requests, tests will be executed and the results
displayed in GitHub interface. We could drop this after we integrate
with our Jenkins instance, or keep using Travis instead.
> Enable continuous integration on Travis-CI

- pdc/apps/auth/tests.py
- pdc/apps/auth/views.py
- pdc/routers.py
This patch adds support for obtaining information about current user
through the API. This can not be used to spy on other users as there is
no input.
Tests are included.
JIRA: PDC-811
> Expose information about current user in API

- pdc/apps/compose/views.py
- pdc/apps/release/tests.py
- pdc/apps/release/views.py
Since we now depend on (currently unreleased) productmd, we need to
update some parts of the code.
This patch updates all mentions of compose ordering in documentation as
well a comment in a test in release app. The test continues to work, the
comment is updated to better explain what is going on.
The remaining parts where productmd is used were all updated before the
open-sourcing. These are release/compose/rpms/image import and exporting
rpm manifest.
There are no code changes, just documentation and comments.
> Update documentation to reflect newer productmd

- .travis.yml
[coveralls.io](https://coveralls.io/github/release-engineering/product-definition-center) is a service for analyzing changes in test code coverage
which is free for open-source projects. This patch uploads coverage
information there so that we can see how it changes.
> Create test coverage report on coveralls.io

- pdc/__init__.py
When the pdc module is imported into another git repo, the version
reported is the version from that repo, not from PDC.
> Get correct version by git describe

- pdc/__init__.py
When pip is installing from github, __file__ is a relative path, and by
skipping to the project root we actually created an empty string. By
making sure we work with absolute path this can be prevented.
> Use absolute path when looking for git repo

- pdc/apps/auth/views.py
If server is configured to use model permissions, each view set must
have a queryset so that there is a place from where to get the
permissions.
> Add queryset to current user API

- contrib/bulk_operations/tests.py
- pdc/apps/common/handlers.py
This should help with troubleshooting problems on devel or qa servers as
the traceback will be in server error log.
There is a change in bulk ops test suite. Some of the tests were
actually wrong and raised an exception for a wrong reason. All exception
logging in those tests is silenced.
This can help development since if there is an unhandled exception
causing 503, the tests now show a traceback of the error instead of just
the failed assertion. There is no change when looking at the bad page in
browser.
> Log exception when 503 is returned

- pdc/apps/package/views.py
In JSON, strings must be wrapped in double quotes. The list of
serializer fields is not actually JSON, but for consistency it makes
sense to use double quotes everywhere.
JIRA: PDC-854
> Fix quotes in documentation of build-images

- pdc/apps/component/serializers.py
- pdc/apps/component/tests.py
The ReleaseField is refactored to be based on SlugRelatedField which
provides error handling consistent with rest of the API.
There is now a test for creating a release component on a non-existing
release.
JIRA: PDC-868
> Report error on creating release component for missing release

- pdc/apps/component/models.py
- pdc/apps/component/tests.py
When there is a group of certain type, make it impossible to delete the
type. The original behaviour was incorrect: the cascading deletes would
not be logged in changeset. Disabling the cascade is both easier and
more practical for the user as deleting the type should be rare.
JIRA: PDC-875
> Don't delete group type with a group

- contrib/bulk_operations/metadata.py
- pdc/apps/release/tests.py
- pdc/settings.py
- pdc/settings_local.py.dist
- pdc/settings_test.py
The metadata generator assumed that when a view responds to a PUT
request, it must be possible to call `get_object` on it to test object
permissions. This is however not the case with bulk operations, which
add PUT to list url. An unhandled AssertionError was raised in that
case.
This patch provides a custom BulkMetadata generator, which is pretty
much the same as the one provided by REST Framework, only it is aware
of the bulk operations.
The settings need to be updated in order for the generator to be used.
All settings files in this repository are updated, but anyone using
settings_local.py need to modify it accordingly.
> Fix internal server error on OPTIONS requests

- pdc/apps/contact/views.py
Add description of the nested identifier in role contacts API. The id
may be useful to some users, even though it is not immediately obvious
whether the id is coming from persons or maillists. This can be deduced
from the keys in the contact.
There should be no possibility of mistake to delete a person instead of
a maillist (or vice-versa). These models are subclasses of the same
parent and should share the same pool of identifiers.
JIRA: PDC-904
> Document id of contact in role-contacts API

- contrib/bulk_operations/bulk_operations.py
- contrib/bulk_operations/tests.py
When user tries to bulk delete data with dicts instead of identifiers,
we should report a sensible error instead of crashing the server.
JIRA: PDC-910
> Handle bad data for bulk delete

- pdc/apps/compose/tests.py
- pdc/apps/package/filters.py
- pdc/apps/package/fixtures/test/rpm.json
- pdc/apps/package/migrations/0004_rpm_linked_releases.py
- pdc/apps/package/models.py
- pdc/apps/package/serializers.py
- pdc/apps/package/tests.py
- pdc/apps/package/views.py
- pdc/apps/release/views.py
1. Add create, update, bulk update methods for RPM so that user
could assign assign rpms to releases.
2. Display compose information in RPM output.
3. Add id field in RPM output, thus also add retrieve method.
> PDC-639 Track rpms in releases and display composes' information in rpm

- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
- pdc/routers.py
Add 2 new end points to take old compose/package
endpoint function.
One is  for a given release and srpm_name list all
composes that contain the package (and include its version).
Another is given a compose _C_ and a package, find the
latest compose older than _C_ which contains a
different version of the package.
Keep the old endpoint same for a while to don't break
existing scripts.
> PDC-645 Refactor compose/package

- contrib/bulk_operations/metadata.py
The AssertionError can only be raised in debug mode. On product server,
the assert is skipped and a KeyError is raised instead.
> Fix bulk metadata generator in production

- pdc/apps/compose/views.py
The list of updatable fields in a compose was missing
rtt_tested_architectures.
JIRA: PDC-928
> Add missing field to compose documentation

- pdc/apps/component/serializers.py
Since the types are not exposed in API currently, we should at least
list them in error message when bad type is given.
> Improve error message for wrong relationship type

- pdc/apps/repository/migrations/0002_auto_20150512_0724.py
It stands for Driver Update Disk. Staging and production servers were
updated already, this is only a fix so that if we ever need to recreate
the database from scratch it will automatically created again.
JIRA: PDC-932
> Add dud as valid content format

- pdc/apps/compose/fixtures/tests/compose_composeimage.json
- pdc/apps/compose/lib.py
- pdc/apps/compose/migrations/0004_auto_20150819_0826.py
- pdc/apps/compose/migrations/0005_auto_20150819_0827.py
- pdc/apps/compose/models.py
- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
- pdc/routers.py
This is a resource that works pretty much the same as compose-rpms. It
allows import compose images and getting the same data back.
The old import API is still available, but marked as deprecated.
Since the existing code did not store path for the images (just the
filename), there are two migrations to get to the desired state. The
first migration deletes all ComposeImage objects, the second creates the
new column in database.
The idea is that deploying on the server and running the migrations will
only lose the minimum amount of data. The images themselves will be
preserved, only their connections to composes will need to be imported
again.
JIRA: PDC-911
> Create compose-images resource

- pdc/apps/utils/SortedRouter.py
- pdc/apps/utils/tests.py
- pdc/routers.py
This patch modifies the router to include all resources in the API root.
It tries various options how to generate an URL. Currently it works with
all existing resources. If in the future we include a resource it can
not generate a url for, the resource will be listed with null url.
There is a bit of a heuristic to avoid generating urls that will lead to
a server crash.
A test is included that tests more special urls.
JIRA: PDC-913
> Display all routes in API root

- pdc/apps/compose/migrations/0005_auto_20150819_0827.py
- pdc/apps/compose/migrations/0006_auto_20150821_0616.py
PostgreSQL does not like a migration to modify data and change the
schema at the same time, so use first migration to fill in missing paths
for compose images and second migration to make the field non-nullable.
> Split compose migrations in two

- pdc/apps/component/migrations/0006_auto_20150818_0614.py
- pdc/apps/component/migrations/0007_auto_20150821_0834.py
This needs to be done before component type is made non-optional and
prevents migration error on PostgreSQL 9.2.
> Add migration to set rpm as type to all components

- pdc/apps/auth/views.py
- pdc/apps/changeset/views.py
- pdc/apps/common/views.py
- pdc/apps/component/views.py
- pdc/apps/contact/views.py
Query params are now spelled consistently.
> Doc spelling update

- pdc/apps/compose/views.py
It is deprecated, but it can still use the new fancy.
> Update link from compose import image

- pdc/apps/component/tests.py
- pdc/apps/component/views.py
The documentation used different format than all other resource.
The create action documentation now does not mention the description
field which is not used anyway. See PDC-611.
The links in documentation lead to page causing internal server error.
While unfortunate, this already happens on global/release component
contacts
> Make doc of global comp. labels consistent

- pdc/apps/common/serializers.py
- pdc/apps/common/tests.py
- pdc/apps/common/views.py
This is consistent with other resources where their string primary
identifier can be changed as well (release_id, product_version_id etc).
This change makes it possible to allow PUT requests to update keys. The
original reason to disable it was because key_id was read-only.
JIRA: PDC-634, PDC-855
> Make sigkey key_id editable

- pdc/apps/repository/filters.py
- pdc/apps/repository/tests.py
Since we expect to have a lot of repos, the filtering should allow
queries with multiple values to choose from (OR). Without this patch,
multiple occurrences of the same filter are accepted, but only the last
value is used for filtering.
JIRA: PDC-970
> Repo filters should accept duplicit filters

- .travis.yml
- Makefile
- pdc/apps/common/tests.py
- tests/__init__.py
- tests/check_api_doc.py
Move test for auto documentation to a separate module that is not
included in make test. The reason for this is that the test hits most
end-points, but does not check much about them. This is raising the test
coverage significantly which could hide bugs.
The test is still run on Travis-CI and can be run locally via
$ make extra_test
JIRA: PDC-975
> Separate auto doc test

- contrib/drf_introspection/serializers.py
- pdc/apps/component/tests.py
- pdc/apps/compose/tests.py
- pdc/apps/package/tests.py
- pdc/apps/release/tests.py
- pdc/apps/repository/tests.py
- pdc/apps/repository/views.py
The fields would otherwise be ignored, which is confusing for the user.
This change required fixing a couple tests. There were tests that
actually checked that the fields are ignored, now they verify that the
request fails.
A bigger change was needed in repository clone view to make sure ids are
not fed into the serializer. This actually fixes an error when
previously the response of repo clone would include old identifiers.
JIRA: PDC-951
> Report error when update specifies a read-only key

- pdc/apps/common/filters.py
- pdc/apps/common/renderers.py
- pdc/apps/package/filters.py
- pdc/apps/package/tests.py
This patch also fixes the documentation to properly show the value
should be an int.
JIRA: PDC-997
> Fix RPM epoch filter to not crash on non-numeric values

- contrib/bulk_operations/bulk_operations.py
- contrib/bulk_operations/tests.py
- docs/source/bulk_operations.rst
- pdc/apps/contact/tests.py
- pdc/apps/package/models.py
- pdc/apps/package/serializers.py
- pdc/apps/package/tests.py
- pdc/apps/release/tests.py
- pdc/apps/repository/tests.py
There are two mostly unrelated patches in this PR. Both come from the same issue. First patch changes the format of error message of bulk update. The second patch fixes how default RPM filename is generated. See commit message of the second patch for more details.
JIRA: PDC-959
> Fixes for default filename

- pdc_client/bin/pdc_client
Print resources in order when running  'pdc_client -s qa ' shell command.
jira: PDC_960
> jira PDC-960, Order resources in client

- pdc/apps/component/views.py
A couple end-points provided incorrect documentation for response when
deleting. The server does not return anything (on success). It is the
client that prints the "No content" message.
JIRA: PDC-980
> Fix empty response docs

- pdc/apps/release/templates/release_detail.html
The paging on that page is not useful in any way. It was previously
disabled through data attributes, but since test server is using an
outdated version of PatternFly and therefore DataTables, this patch
explicitly disables the paging with JavaScript.
JIRA: PDC-978
> Disable paging of repos in release detail

- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
Return 404 instead of 200 if not found any matched objects.
JIRA: PDC-940
> "not found" enhancement for buld destory overrides with query param.

- pdc/apps/release/views.py
Cloning has some advantages over creating a new release from scratch.
The documentation for create is updated to link to the clone API.
Some information was missing in the clone doc, it is added now.
JIRA: PDC-355
> Promote cloning instead of creating new releases

- pdc/apps/package/models.py
The changesets were missing this field. There is still a field
`linked_composes` that is not included in the changeset. This is because
the field can not change through any API.
JIRA: PDC-995
> Include RPM filename in changeset

- pdc/apps/common/filters.py
- pdc/apps/common/hacks.py
- pdc/apps/compose/views.py
- pdc/apps/package/filters.py
- pdc/apps/package/migrations/0005_auto_20150907_0905.py
- pdc/apps/package/models.py
- pdc/apps/package/serializers.py
- pdc/apps/package/tests.py
- pdc/apps/package/views.py
Each RPM can have arbitrary number of dependencies of multiple types.
The types are hard-coded, and can not be extended at run-time.
With this patch, it is possible to store and retrieve the dependencies.
There are tests for these parts.
Existing tests have been updated to pass: for RPM tests there are some
minor updates. The compose/package API and its variants are updated not
to include dependencies in their output.
All changes to dependencies are logged in change sets as single update
to the RPM.
The filtering support is not finished yet. So far it is only possible to
get RPMs that depend on a given package with optional equality version
constraint. This is not documented nor covered with unit tests.
JIRA: PDC-955
> Enable storing RPM dependencies

- pdc_client/pdc-client.spec
Fix JIRA: PDC-1015
NOTE: 'pdc-test' copr repo got updated, after we `tito tag` for pdc-client, this will work for 'pdc' repo as well.
> Add the missing BuildRequires 'python' for pdc_client.

- pdc/apps/common/templates/browsable_api/api.html
This way it is possible to link to a specific part of the documentation,
not just the list. The whole page is in the history only once, so if
user goes from API root to a resource and clicks all tabs there, a
single click on back button will bring them back to API root.
JIRA: PDC-1011
> Show current tab in URL

- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
When requesting an older compose with different version of an RPM, the
composes from previous releases of the same product are explored as
well.
When going back, only GA releases are considered. This way, when
starting from compose for r-1.1-updates or r-1.2, composes from r-1.0
and r-1.1 will be considered, but not from r-1.0-updates.
r-1.0 --------+- r-1.0-updates -----
|
\- r-1.1 -----+- r-1.1-updates -----
|
\- r-1.2 -----
JIRA: PDC-1008
> Find older compose from other releases

- pdc_client/__init__.py
- pdc_client/bin/pdc_client
Since the new client has abstraction around BeanBag, this class can be
used in the original client. The PDCClient class is updated in this
patch to support change comment.
There should be no change in the functionality of the old client.
However, without automated tests, it's hard to say for sure.
> Use helper class in original client

- rel-eng/packages/.readme
- rel-eng/tito.props
This directory was auto generated and merged when played tito.
Need to be removed.
> Remove rel-eng directory

- .travis.yml
- docs/.gitignore
- docs/LICENSE_sphinx_deployment
- docs/Makefile
- docs/sphinx_deployment.mk
now the gh-pages branch is available. It uses the very project mentioned in the desc ：sphinx-deployment
it requires 2 steps to update the docs:
1. run `make html` in `docs` directory
2. run `make deploy_gh_pages` in `docs` directory
when pushed, travis-CI will be triggered to auto-regenerate sphinx docs and push the generated html to gh-pages branch.
and the result can be viewed in http://release-engineering.github.io/product-definition-center/
> PDC-1020 Create github pages with rendered docs

- pdc/apps/component/models.py
- pdc/apps/component/signals.py
- pdc/apps/osbs/signals.py
- pdc/apps/osbs/tests.py
When a new release is cloned from an old one, its components will get
cloned. With this patch, the osbs record is cloned as well, so the list
will not need to be populated again.
JIRA: PDC-958
> Clone OSBS together with components

- pdc/apps/common/renderers.py
- pdc/apps/component/filters.py
- pdc/apps/component/migrations/0010_migrate_existing_contacts.py
- pdc/apps/component/models.py
- pdc/apps/component/serializers.py
- pdc/apps/component/tests.py
- pdc/apps/component/views.py
- pdc/apps/contact/apps.py
- pdc/apps/contact/fixtures/tests/contact_role.json
- pdc/apps/contact/migrations/0002_auto_20151001_1239.py
- pdc/apps/contact/migrations/0003_auto_20151001_1309.py
- pdc/apps/contact/models.py
- pdc/apps/contact/serializers.py
- pdc/apps/contact/signals.py
- pdc/routers.py
With this API, there is no inheritance between release and global
components. Instead, what would previously be inherited is stored
directly on a release component.
The relationship between a component and a contact is simplified to a
regular Many-to-Many relationship with an intermediate model to point to
role for that contact.
In this patch, new API is added and old tests are adapted to verify it
is correct. There is database schema migration, but the current data is
not migrated.
> Create new contact API

- pdc/apps/common/hacks.py
- pdc/apps/compose/lib.py
- pdc/apps/release/lib.py
The common.hacks module defines a couple functions for loading
composeinfo, RPM and image manifests. The methods expect output as a
dict, so they should not be named `_from_str`.
> Rename helper function

- pdc/apps/release/lib.py
- pdc/apps/release/tests.py
It can easily happen that the release version is bumped but not its
integrated layered products. The import fails in such case. Now there is
a clear error message explaining what the problem is.
JIRA: PDC-1033
> Give better error message when importing incorrect composeinfo

- pdc_client/plugins/component.py
- pdc_client/plugins/release.py
- pdc_client/plugins/rpm.py
- pdc_client/tests/rpm/tests.py
The usage should not wrap required arguments in brackets. The fixed
create commands are for release, rpm, global and release components.
The test for creating RPMs was updated to list all required arguments.
JIRA: PDC-1084, PDC-1079
> Mark required arguments in client create

- pdc/apps/release/serializers.py
- pdc/apps/release/tests.py
Resetting base products was implemented in previous patch. Product
version should have been updated to work the same way, but was
forgotten. Test is added.
JIRA: PDC-1095
> Allow resetting product version

- pdc_client/plugins/release.py
- pdc_client/tests/release/data/detail.txt
All other places refer to the value as "release type". It is better to
keep the work release in the label in the client.
JIRA: PDC-1068
> Rename release type field in client output

- pdc/apps/partners/admin.py
- pdc/apps/partners/filters.py
- pdc/apps/partners/migrations/0001_initial.py
- pdc/apps/partners/models.py
- pdc/apps/partners/serializers.py
- pdc/apps/partners/tests.py
- pdc/apps/partners/views.py
- pdc/routers.py
- pdc/settings.py
When delivering data to customers, some partners may have access to
various data before general availability. It is necessary to store this
kind of information. This patch adds storage for partner metadata and
allows linking partners to specific Variant.Arches on releases.
Partner data can be completely edited through the API as well as the
mapping. Partner types can only be modified in Django admin.
JIRA: PDC-1048
> Add support for storing partner information

- pdc/apps/partners/migrations/0002_auto_20151015_1042.py
- pdc/apps/partners/models.py
The original issue was not clear on ftp_dir and rsync_dir fields. The
were always required. Turns out the fields should not be. This patch
changes them to accept empty string as possible value.
JIRA: PDC-1048
> Allow empty directories for partners

- pdc/apps/common/views.py
Up to now, the list was sorted based on the order in which arches were
created. With manually added ones, the order was not correct.
JIRA: PDC-1107
> Sort arches in web view

- pdc_client/plugin_helpers.py
- pdc_client/plugins/component.py
- pdc_client/plugins/release.py
- pdc_client/plugins/rpm.py
Required arguments for create commands are now displayed in a separate
block. For update action, all the arguments end up in one block.
JIRA: PDC-1079
> Improve help output for create commands

- pdc/apps/common/renderers.py
- pdc/apps/common/tests.py
First patch fixes a bug about documentation, second patch adds some tests for serializer documenatation generator. The patches are not really closely related, but the second depends on the first one (due to changed output).
> Serializer documentation fix + tests

- pdc/apps/common/handlers.py
- pdc/apps/common/tests.py
- pdc/apps/common/views.py
- pdc/urls.py
When Django generates 404 response, it would always return the rendered
template, which is not nice as the client might be expecting JSON. This
patch adds a check for the Accept HTTP header. If it mentions
application/json MIME type, JSON object is returned instead.
This is automatically picked by pdc_client as it already adds the
header.
JIRA: PDC-1106
> Return JSON 404 response from Django

- pdc/apps/component/views.py
Both release component contacts and global component contacts show GET
method for destroying, which is obviously wrong.
JIRA: PDC-1112
> Fix wrong method in contact documentation

- pdc/apps/contact/migrations/0005_auto_20151027_0725.py
- pdc/apps/contact/models.py
- pdc/apps/contact/serializers.py
- pdc/apps/contact/tests.py
- pdc/apps/contact/views.py
Accept `"unlimited"` as valid input for role count limit and fix the examples.
> Role count limit improvements

- requirements/production.txt
Add the limit to not use Django REST Framework v3.3.0
until we're ready.
> Not ready to use DRFv3.3.0

- pdc/apps/compose/views.py
- pdc/apps/release/models.py
- pdc/apps/release/templates/product_detail.html
- pdc/apps/release/templates/product_version_detail.html
- pdc/apps/release/templates/release_detail.html
- pdc/apps/release/tests.py
- pdc/apps/release/views.py
Many of the pages performed lots of database queries. By selecting and
prefetching related data, that number can be brought down significantly.
This patch required rewriting the logic for determining if product or
product version is active. Now it  able to take advantage of the
preloaded data. A test case was added to make sure it works correctly.
JIRA: PDC-1132
> Improve performance of the web UI

- pdc/apps/component/serializers.py
- pdc/apps/component/tests.py
The code in component serializer  is not reachable,
and remove the unreachable code.
JIRA: PDC-1053
>  Update the release component serializer file

- pdc_client/plugin_helpers.py
- pdc_client/plugins/build_images.py
- pdc_client/plugins/component.py
- pdc_client/plugins/compose.py
- pdc_client/plugins/image.py
- pdc_client/plugins/permission.py
- pdc_client/plugins/release.py
- pdc_client/plugins/rpm.py
- pdc_client/runner.py
- pdc_client/tests/build_image/tests.py
- pdc_client/tests/component/tests.py
- pdc_client/tests/compose/tests.py
- pdc_client/tests/image/tests.py
- pdc_client/tests/release/tests.py
- pdc_client/tests/rpm/tests.py
The original command structure goes like `pdc COMMAND` and now it looks like `pdc COMMAND SUB-COMMAND`. The functions of the original commands are not altered.
JIRA: PDC-1129
> Restructure pdc client command structure

- pdc/apps/release/templates/product_pages.html
- pdc/apps/release/templates/release_pages.html
- pdc/apps/release/views.py
- pdc/urls.py
Move the base-product link from 'Releases'  to  'Products' in WebUI menu,
At the same time, update the release view.py file;
and remove the unreachable file.
JIRA: PDC-1091
>  Restucture the webUI

- pdc/settings.py
Sending credentials is now enabled by default. The change comment header
is whitelisted and can be used from UIs.
A bunch of explanatory comments was added to the settings file with
pointers on what might be reasonable to override in local settings.
JIRA: PDC-1088
> Modify default CORS settings

- pdc/apps/partners/filters.py
- pdc/apps/partners/tests.py
It should be possible to filter partners by name or type. Tests have
been added to verify this feature is present.
JIRA: PDC-1164
> Add missing filters to partners list

- MANIFEST.in
JIRA: PDC-1094
Exclude the pdc_client module as it is packaged independently with tito
> Exclude pdc-client from distribution package

- docs/source/api_devel.rst
- docs/source/development.rst
- docs/source/index.rst
Add general tips for creating new API. The goal is to have all the information summarized in one place, so that nothing is forgotten when new resources are added.
> Development docs

- pdc_client/plugins/component.py
- pdc_client/tests/component/tests.py
> pdc command take release and name as parameters instead of id.

- pdc/apps/package/filters.py
- pdc/apps/package/serializers.py
- pdc/apps/package/tests.py
- pdc/apps/package/views.py
1. Add format filter for resource build-image-rtt-tests
2. Fix a output bug.
JIRA: PDC-1205
> Add format filter for build-image-rtt-tests and fix a bug.

- pdc/apps/compose/filters.py
- pdc/apps/compose/fixtures/tests/compose_composeimage.json
- pdc/apps/compose/migrations/0008_composeimage_rtt_test_result.py
- pdc/apps/compose/models.py
- pdc/apps/compose/routers.py
- pdc/apps/compose/serializers.py
- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
JIRA: PDC-1191
With the constraint that each compose in specific variant arch the image `file_name` instead of (`file_name`, `sha256`) is unique, we could use `compose/variant/arch/file_name` as lookup key.
> Add compose image RTT tests APIs.

- pdc/apps/common/handlers.py
When called compose-rpms api and rpm date info was
not correct, productmd would throw ValueError exception and
cause server internal error (500 error).
Now let exception_handler handle ValueError exception then server
will response http code 400 and meaningful message.
> Handle ValueError in exception_handler

- pdc/apps/compose/serializers.py
- pdc/apps/compose/tests.py
1. Use compose id as compose out put, not compose model unicode.
So the filter and output is consistent.
2. Response test_result illegal with default ChoiceSlugField behavior.
It is more clear.
JIRA: PDC-1191
> Some improvements for stare image test results.

- pdc/apps/component/tests.py
- pdc/apps/release/views.py
This patch will add error info when Source_release or Target_release
is not existed. And then, update the decription in webUI.
JIRA:PDC-1204
> Add error info when input error para

- pdc/apps/package/tests.py
- pdc/apps/package/views.py
Update or retrieve the build-image-rtt-tests api with
build_nvr/format instead of ID.
JIRA: PDC-1248
> Allow PATCH on build-image-rtt-tests with build_nvr/format

- pdc/apps/compose/views.py
- pdc/apps/release/lib.py
- pdc/apps/repository/tests.py
There is not response formate in docs of retrieve and update
method in composes/{compose_id}/rpm-mapping/{package}.
JIRA: PDC_1257
> Add response info for composes/{compose_id}/rpm-mapping/{package}

- pdc/apps/compose/lib.py
- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
- pdc/apps/release/lib.py
- pdc/apps/release/tests.py
- pdc/apps/release/views.py
1. Return count of the images/rpms when importing image-manifes and rpm-manifest.
2. Return url when importing release from composeinfo.json
JIRA: PDC-1268
> Improve output when successfully import files composeinfo.json/rpm-manifest.json/image-manifest.json

- pdc/apps/common/constants.py
- pdc/apps/common/viewsets.py
- pdc/apps/component/views.py
- pdc/apps/compose/tests.py
- pdc/apps/utils/utils.py
Warning could be put into this field. Currently, it is
added into the response from NoEmptyPatchMixin when
patch or update with empty data.
JIRA: PDC-1283
> Provide a response header field name "PDC-Warning"

- pdc/apps/component/tests.py
- pdc/apps/release/views.py
For rpc/release/component-clone, when source-release doesn't contain
component, return error info for user.
JIRA: PDC-1282
> Return error info When srouce release doesn't contain component

- pdc/apps/common/filters.py
- pdc/apps/contact/filters.py
- pdc/apps/contact/tests.py
User could filter release component contacts or golbal component
contacts by component name with regexp.
The implementation is based on Django query set regexp implementation.
So they should have the same limitations.
JIRA: PDC-1285
> Add support for regexp for contact searches by component name

- pdc/apps/component/tests.py
- pdc/apps/component/views.py
As JIRA shows,the update method of release-component have
updated,  and this task don't need to do.
JIRA: PDC-945
> Remove the unavailable code

- pdc/apps/compose/serializers.py
When variant para is missing or unavailable, return clear error info for user. 
JIRA: PDC-1232
> Update the error info for compose-tree-location

- pdc/apps/compose/serializers.py
- pdc/apps/contact/views.py
When Arch para exist in data but doesn't exist in given
compose/variant branch, return detail error info.
JIRA: PDC-1232
> Add more detail error info for compose-tree-locations

- pdc/apps/release/views.py
Becuase resource variant-types is renamed to release-variant-types.
JIRA:  PDC-1338
> Change links from varianttype-list to releasevarianttype-list.

- pdc/pdc-sync-ldap
If a member is staff but not in any group other than
user group itself, set the user to inactive and remove
from all groups in PDC.
JIRA: PDC-1345
> Remove permissions from inactive user accounts

- pdc/apps/compose/routers.py
- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
This API was claimed deprecated in 0.6.0 (PDC-911)
JIRA: PDC-1370
> Remove deprecated API /rpc/compose/import-images/

- pdc/apps/compose/templates/compose_list_include.html
- pdc/static/pdc/style.css
There will be a line cross the deleted compose and
text will be faded out in web UI.
JIRA: PDC-1347
> Display deleted compose with special style in web UI.

- pdc/apps/compose/fixtures/tests/image-manifest.json
- pdc/apps/compose/lib.py
- pdc/apps/compose/views.py
- pdc/apps/package/migrations/0012_image_payload.py
- pdc/apps/package/models.py
Productmd has merged a patch that add an extra field `subvariant` to image manifest. This in turn broke PDC test suite. This patch should update PDC to be able to store and return that value.
> Add subvariant field to images

- pdc/apps/repository/views.py
Remove useless header informations for some APIs, include: content-delivery-content-categories, content-delivery-content-formats, content-delivery-repo-families, content-delivery-repos, content-delivery-services.
JIRA:PDC-1376
> Remove useless header informations for some APIs

- pdc/apps/compose/serializers.py
In "create"  method  doc of compose-tree-location API, variant type is unknown; to show its type for user.
JIRA: PDC-1387
> Write correct variant type in compose-tree-location_doc

- pdc/apps/compose/migrations/0009_auto_20160321_0855.py
- pdc/apps/compose/models.py
- pdc/apps/compose/serializers.py
- pdc/apps/compose/tests.py
When with same compose/variant/arch/location and diff scheme, it also can create a instance for Compose-tree-locations.
JIRA: PDC-1389
> Compose-tree-locations be unique over scheme

- pdc/apps/compose/templates/compose_detail.html
When the value of Arch with a long string, align left.
JIRA: PDC-1226
> Visible for Arch names on compose page

- pdc/apps/release/fixtures/tests/base_product.json
- pdc/apps/release/lib.py
- pdc/apps/release/migrations/0004_auto_20160308_1614.py
- pdc/apps/release/migrations/0005_auto_20160314_1532.py
- pdc/apps/release/models.py
- pdc/apps/release/serializers.py
- pdc/apps/release/templates/base_product_detail.html
- pdc/apps/release/templates/base_product_list_include.html
- pdc/apps/release/templates/release_detail.html
- pdc/apps/release/tests.py
Added release_type to BaseProduct.
Validation of Release, ProductVersion, Product and BaseProduct fields is based on regexps from productmd.
Change release_ids to use '@' as separator between release and base product part.
Release_type can be in both parts of release_id now (for example foo-1.0-updates@fedora-23-updates).
> Productmd changes

- pdc/apps/compose/lib.py
- pdc/apps/compose/migrations/0010_auto_20160407_1322.py
- pdc/apps/compose/models.py
- pdc/apps/compose/tests.py
Stare relative paths when importing compose images and compose
rpms. The path is stored with compose, variant, arch, path type.
JIRA: PDC-1358
> Store relative paths to variant/$arch/$content_category_name dir

- pdc/apps/repository/models.py
- pdc/apps/repository/tests.py
When converting data from ET to PDC, the restrictions on repo names (which are there for a good reason) don't meet with historical data:
* Updates releases can contain EUS and AUS repos
* EUS releases can contain AUS repos
The checks to be modified or disabled in order to be able to import the data.
JIRA: PDC-1426
> Dsable eus/aus repo checks

- pdc/apps/common/filters.py
- pdc/apps/common/tests.py
- pdc/apps/compose/filters.py
- pdc/apps/compose/fixtures/tests/more_composes.json
- pdc/apps/compose/tests.py
- pdc/apps/release/filters.py
- pdc/apps/release/tests.py
- pdc/apps/release/views.py
- pdc/apps/repository/filters.py
- pdc/apps/repository/tests.py
It doesn't make sense to enable multi value for following param.
1. Boolean param.
2. Param with substring match.
3. Param with few kinds of type.
NullableCharFilter and MethodFilter with special filter logic
are not enabled as well.
JIRA: PDC-1459
> Enable query with multi values.

- pdc/apps/compose/models.py
- pdc/apps/release/tests.py
- pdc/apps/release/views.py
For releases/{release_id}/rpm-mapping API, when
release has no compose. Set compose rpm mapping
part as empty dict and perform other steps.
JIRA: PDC-1461
> Get rpm-mapping when release has no compose.

- pdc/apps/compose/templates/overrides_form.html
- pdc/apps/compose/views.py
Handle relase has no compose in 'Manage Overrides' detail page.
'Based on' string is removed and overrides are displayed.
JIRA: PDC-1466
> Handle release has no compose in web UI

- Dockerfile
https://copr.fedoraproject.org/coprs/patternfly/patternfly1/repo/fedora-21/patternfly-patternfly1-fedora-21.repo has been replaced by a HTTP redirect to https://copr.fedorainfracloud.org/coprs/patternfly/patternfly1/repo/fedora-21/patternfly-patternfly1-fedora-21.repo
Instead of replacing the URL, make curl follow the redirect
> instruct curl to follow HTTP redirect

- pdc/apps/auth/tests.py
- pdc/apps/changeset/middleware.py
- pdc/apps/changeset/tests.py
- pdc/settings.py
If the number of a changeset's change reach
or greater threshold (CHANGESET_SIZE_ANNOUNCE)
and CHANGESET_ANNOUNCE_EMAIL is set in settings.
Then send a email with necessary content.
JIRA: PDC-1441
> Announce big changes in PDC database

- pdc/apps/auth/views.py
- pdc/apps/utils/middleware.py
- pdc/settings.py
Now when a special parameter 'create' set to true in
resource permissions list method. It will generate
resource permissions.
The old middleware way looks not work well in production
environment.
JIRA: PDC-1380
> Change the way to generate resource permissions automatically.

- pdc/apps/auth/permissions.py
- pdc/apps/auth/tests.py
- pdc/apps/auth/views.py
- pdc/apps/changeset/views.py
- pdc/apps/common/views.py
- pdc/apps/compose/views.py
- pdc/apps/package/views.py
- pdc/apps/release/views.py
- pdc/apps/repository/views.py
- pdc/apps/utils/utils.py
1. Put permission control on some resources that only
have read method. Because PDC currently grant users
read permission in default, these APIs should be treated
as others.
2. If user is granted read permission by configurations,
display the correct permissions in real.
3. auth/current-user and auth/current-user are still not
included in permission control
JIRA: PDC-1543
> Put permission control on more resources and show correct permissions.

- pdc/apps/compose/filters.py
- pdc/apps/compose/models.py
- pdc/apps/compose/routers.py
- pdc/apps/compose/serializers.py
- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
In Compose API, the paramenter of rtt_tested_architectures is deeply nested
and hard to use/filter etc. So we want to create compose-tree-rtt-tests
endpoint which would only do RTT tests - nothing else.
JIRA: PDC-1316
> Create new API of compose-tree-rtt-tests

- docs/source/using_api.rst
- default values of optional arguments
If default value of optional argument changes, existing API users could
suddenly supply incomplete/incorrect information for their use case
- order of returned results
If order of multiple results changes it can affect how it's interpreted by the
clients. For example releases returned for given product ID, or composes for
given release ID.
Change-Id: Icfc10ce5db2d90fae56e0debbcc2476a11494471
> Add two new rules to API stability

- pdc.spec
> Specify Django version less than 1.9 in spec file.

- contrib/drf_introspection/__init__.py
- pdc/apps/common/viewsets.py
- pdc/apps/compose/views.py
- pdc/apps/release/fixtures/tests/release_groups.json
- pdc/apps/release/tests.py
- pdc/apps/release/views.py
- pdc/settings.py
- pdc/settings_test.py
1. Add the OrderingFilter class supports simple query parameter
controlled ordering of results.
2. This feature is availbale for these APIs which have the 'List'
method and have the filter attribute.
3. The value which ordering key mapped is contained in given
serializer_class field.
JIRA: PDC-1512
> Take keys into acount for ordering of all APIs

- pdc/apps/auth/serializers.py
- pdc/apps/auth/tests.py
- pdc/apps/auth/views.py
Use one layer data in creating, updating and response
instead of old two layers data in group resource permissions
API.
JIRA: PDC-1551
> Unnest group resource permissions create/update/response data.

- pdc/apps/common/renderers.py
- pdc/apps/common/viewsets.py
When override the ordering of the results, some changes happened;
as followed:
1, Update the ordering fields. the ordering fields are the intersection
of Model fields and Serializer fields.
2. To make the ordering fields more friendly and clearly for customers,
add the ordering fields in docs, which share in page of 'LIST' method.
JIRA:PDC-1659
> Update the docs and add the ordering fields

- pdc/apps/bindings/apps.py
- pdc/apps/common/apps.py
- pdc/apps/component/apps.py
- pdc/apps/compose/apps.py
- pdc/apps/contact/apps.py
- pdc/apps/package/apps.py
- pdc/apps/release/apps.py
- pdc/apps/repository/apps.py
Fixes: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
The fix only moves signal imports under ready() method.
> Fix apps loading in Django 1.9.

- pdc/apps/release/templates/base_product_list_include.html
- pdc/apps/release/templates/product_list_include.html
- pdc/apps/release/templates/product_version_list_include.html
- pdc/apps/release/templates/release_detail.html
- pdc/apps/release/templates/release_list_include.html
- pdc/apps/release/views.py
- pdc/urls.py
When using multiple PDC instances, it's difficult to preserve URLs,
since the IDs for a release/productversion/product can differ.
Using slug field solves the problem.
> Use slug in release / product version / product URLs.

- pdc/apps/component/migrations/0012_auto_20160928_1838.py
- pdc/apps/component/models.py
- pdc/apps/component/serializers.py
- pdc/apps/component/tests.py
This used to consider only `name` and `release`, which makes a certain
amount of sense.  We don't want more than one rpm with the same name in
the same release entry here.
However, if we open this up to start handling other types of release
components like `container` or `module`, then it is easy to imagine that
we might have one "cockpit" rpm in a release but also a "cockpit"
container in the same release.
If you try to create both of those entries in PDC, it will fail saying
that "name and release must be unique".  This change fixes that by
loosening the uniqueness constraint to also take `type` into account.
> Make release components be unique by name/release/type.

- pdc/apps/auth/backends.py
- pdc/settings.py
We'd like to try this out in Fedora.
> Allow using mod_auth_oidc for remote user auth.

- pdc/apps/common/views.py
The `exception` argument to `page_not_found` is *required* in django-1.9 but
does not exist in django-1.8 and earlier.
> Handle new page_not_found argument in django-1.9.

- docs/source/development.rst
- pdc/settings_local.py.dist
- requirements/devel.txt
- requirements/production.txt
These are simple fixes to get the pdc server up and running both in docker (with Dockerfile in this repo) and virtualenv (on Fedora 25).
> Fixes for initial build and run

- pdc.spec
- pdc/apps/module/migrations/0001_initial.py
- requirements/devel.txt
- requirements/production.txt
JIRA: PDC-2082
---
Strange that pylint nor flake8 tool don't warn about this unused import.
> Remove unneeded django-jsonfield dependency

- pdc/apps/release/filters.py
- pdc/apps/release/migrations/0009_variantcpe.py
- pdc/apps/release/models.py
- pdc/apps/release/routers.py
- pdc/apps/release/serializers.py
- pdc/apps/release/tests.py
- pdc/apps/release/views.py
Adds new model binding CPE to release-variant because the permission to
change CPE should be left only to authorized person (security team).
JIRA: PDC-1319
---
CPE in the `release-variants` listing but it's only backreference from `VariantCPE` model (`variant-cpes` in API) so it cannot be changed from `release-variants` which makes it possible to set different permissions.
> Add CPE field to release-variant endpoint

- pdc/apps/release/filters.py
- pdc/apps/release/fixtures/tests/allowed_push_targets.json
- pdc/apps/release/migrations/0014_auto_20170922_0804.py
- pdc/apps/release/models.py
- pdc/apps/release/serializers.py
- pdc/apps/release/tests.py
- pdc/apps/repository/filters.py
- pdc/apps/repository/fixtures/tests/push_target.json
- pdc/apps/repository/migrations/0003_pushtarget.py
- pdc/apps/repository/models.py
- pdc/apps/repository/routers.py
- pdc/apps/repository/serializers.py
- pdc/apps/repository/tests.py
- pdc/apps/repository/views.py
---
I have yet to implement tests and fix existing ones.
Field `allowed_push_targets` is implemented in products, product-versions, releases, release-variant. Only for products it's saved as-is; for other endpoints, `masked_push_targets` is stored instead but user will still only see `allowed_push_targets` in requests and responses.
Examples:
```bash
> pdc_client -r content-delivery-services
{
"count": 3,
"next": null,
"previous": null,
"results": [
{
"description": "Red Hat Network",
"name": "rhn"
},
#...
]
}
> pdc_client -r push-targets -x POST \
-d '{"description":"", "name":"rhn-stage", "service":"rhn"}'
{
"description": "",
"host": "",
"id": 1,
"name": "rhn-stage",
"service": "rhn"
}
> pdc_client -r push-targets -x POST \
-d '{"host":"", "description":"RHN Live", "name":"rhn-live", …
```
> Pdc 1895 push targets

- pdc/apps/common/handlers.py
Prints the same response disregarding the DEBUG option value.
Avoids printing annoying HTML backtrace with command line tools.
> Omit changing response for DEBUG mode

- pdc/settings_test.py
By default test database is in-memory (':memory:'), i.e. not saved on
disk, making it impossible to skip migrations to quickly re-run tests
with '--keepdb' argument.
> Use persistent test DB (--keepdb can skip migrations)

- pdc/apps/repository/filters.py
- pdc/apps/repository/tests.py
Adds filter fields `origin_repo_release_id` and
`destination_repo_release_id`.
JIRA: PDC-1970
---
I forgot to add filtering (mentioned in JIRA) in previous PR.
> Filter multi-destinations by repo release_id

- pdc/apps/module/tests.py
- pdc/apps/module/views.py
This PR:
* Adds a delete test for the unreleasedvariants API
* Remove unused 'lookup_regex' variable. The original author must have meant to use 'lookup_value_regex'
* Fixes the URL format in the unreleasedvariants documentation
> Various fixes for the unreleasedvariants API

- pdc/apps/module/tests.py
- pdc/apps/module/views.py
For some reason after updating from our forked instance of PDC in Fedora to the latest upstream, we seem to have lost the ability to update items in the unreleasedvariants API. This fixes that.
> Fix the PATCH API in unreleasedvariants

- pdc/settings_common.py
Removes "make sure URL includes trailing slash" from unrelated update
errors (empty request data).
JIRA: PDC-2298
> Remove "trailing slash" hint from errors

- pdc/apps/utils/utils.py
ReleaseBrewMapping is OneToOneRel to Release, not part of
Release model. Need to be supported seperately.
JIRA: PDC-2208
> Support OneToOneRel in RelatedNestedOrderingFilter

- examples/contact-browser/package.json
There is CVE-2015-8858 for uglify-js versions below 2.6.0.
This was detected and suggested by github [1].
[1] https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/
> Bump uglify-js version in example

- pdc/apps/release/views.py
Listing releases with lots of related composes caused SQL query for
prefetching to have too many parameters.
The prefetch query looks like this:
SELECT "compose_compose"."id", "compose_compose"."release_id", ...
FROM "compose_compose"
WHERE "compose_compose"."release_id" IN (1, 2, /* ... too many IDs */)
JIRA: PDC-1733
---
Haven't seen any performance regression but I tested this only with ~170 related composes.
> Fix long SQL query for releases

- pdc/apps/module/filters.py
- pdc/apps/module/migrations/0007_unreleasedvariant_context_field.py
- pdc/apps/module/migrations/0008_unreleasedvariant_make_variant_uid_unique.py
- pdc/apps/module/models.py
- pdc/apps/module/serializers.py
- pdc/apps/module/tests.py
- pdc/apps/module/views.py
This PR adds the "variant_context" field to the unreleasedvariants API. This field is used to identify a module build with the same name (variant_name), stream (variant_version), and version (variant_release).
This PR also fixes a bug where uniqueness is not enforced on the "variant_uid" field.
> Add the "variant_context" field to the unreleasedvariants API

- Dockerfile
- external graphviz repository URL is no longer valid
- drop the dependency on the external graphviz repository since
a previous commit changed the container to use Fedora which
provides a suitable version of graphviz
Signed-off-by: Robert Marshall <rmarshall@redhat.com>
> Container build throws 404 error on graphviz repo

- pdc/apps/module/__init__.py
- pdc/apps/module/admin.py
- pdc/apps/module/apps.py
- pdc/apps/module/filters.py
- pdc/apps/module/migrations/0009_v2.py
- pdc/apps/module/models.py
- pdc/apps/module/routers.py
- pdc/apps/module/serializers.py
- pdc/apps/module/tests.py
- pdc/apps/module/views.py
- pdc/apps/unreleasedvariant/__init__.py
- pdc/apps/unreleasedvariant/apps.py
- pdc/apps/unreleasedvariant/filters.py
- pdc/apps/unreleasedvariant/routers.py
- pdc/apps/unreleasedvariant/serializers.py
- pdc/apps/unreleasedvariant/tests.py
- pdc/apps/unreleasedvariant/views.py
- pdc/settings_common.py
Add v2 of the "unreleasedvariants" API called "module" and correct the docs in "unreleasedvariants"
To use v1 of the API, continue using the "unreleasedvariants" API but for v2, use the "module" API.
The new version of the API does the following:
* Renames "variant_name" to "name"
* Renames "variant_version" to "stream"
* Renames "variant_release" to "version"
* Renames "variant_context" to "context"
* Renames "variant_uid" to "uid"
* Drops the usage of "variant_type" (now set to "module" in the DB)
* Drops the usage of "variant_id" (now set to the module name in the DB)
* "uid" is now read-only and the value is derived as "name:stream:version:context"
> Add v2 of the "unreleasedvariants" API called "module"

- .travis.yml
- Dockerfile
- docs/source/development.rst
- pdc.spec
- pdc/apps/compose/filters.py
- pdc/apps/compose/lib.py
- pdc/apps/package/models.py
- pdc/apps/utils/rpm.py
- pdc/apps/utils/tests.py
Package kobo-rpm requires rpm to be installed on system. This can be
problem for some distributions like Ubuntu which is used by Travis CI.
As solution, parse_nvr() and parse_nvra() are implemented in PDC. The
new functions use regular expressions constructed from simple formatted
strings.
Tests are taken from kobo. There are few additional ones so that every
regular expression matches at least once.
> Replace kobo-rpm dependency with own functions

- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
- pdc/apps/release/models.py
- pdc/apps/release/tests.py
When a compose is marked as deleted, it should not show up by default in some places. The compose list has a filter, so there it's ok.
This patch fixes and tests that compose_set in /releases/ API does not include deleted composes (either directly connected or linked).
Also the lower level method used to get latest compose for a release is tested to not include deleted ones. This should fix RPM Mapping API end-point.
The APIs to get compose by release or product version and RPM NVR are updated to not return deleted composes.
JIRA: PDC-2533
> Fix displaying deleted composes

- pdc/apps/common/viewsets.py
- pdc/apps/module/tests.py
- pdc/apps/unreleasedvariant/tests.py
The default router will not allow the field in URL to contain a dot: it fails to create the URL in that case. This patch sets a regex so that the UID can be anything without a slash.
JIRA: PDC-2535
> Fix access to modules with dot in UID

- pdc/apps/module/filters.py
- pdc/apps/module/tests.py
- pdc/apps/unreleasedvariant/tests.py
Due to how the new API works, the same filter can be added to unreleased variants for free. Tests are added in both APIs.
JIRA: PDC-2382
> Filter modules by RPM filename

- docs/source/using_api.rst
By default, GET requests don't require authentication. This can be
changed by adding ``ALLOW_ALL_USER_READ = False`` in settings.
JIRA: PDC-1841
> Fix authentication documentation

- pdc/apps/auth/views.py
A class implementing a particular resource can be moved to a different Python module, which changes the string it can be converted to. If this happens, generating new permissions will fail because of violating a unique constraint on the resources.
JIRA: PDC-2573
> Update resources when needed

- pdc/apps/compose/lib.py
- pdc/apps/compose/tests.py
- pdc/apps/compose/views.py
- pdc/apps/utils/messaging.py
Instead of ignoring them all, it should log them. This can be easily disabled in the LOGGING settings by adding following snippet:
'pdc.apps.utils.messaging': {
'level': 'WARNING',
}
JIRA: PDC-2583
> Dummy messenger should log the messages

- pdc/apps/release/forms.py
They should search in the full ID. Since it contains short and version, we can remove those two fields.
PDC-2478
> Fix search forms for base product and product version

- pdc/apps/module/serializers.py
- pdc/apps/package/views.py
This applies to modules and build-images API.
* Explictly say that the value is NEVRA with `.rpm` suffix
* Mention that `srpm_nevra` is required when creating modules.
> Improve documentation for rpms field

- pdc/settings_common.py
The default config file now has comments explaining what the options actually do.
DIST_GIT_WEB_ROOT and DIST_GIT_RPMS_PATH options are no longer mentioned. They were not used anywhere else but to construct DIST_GIT_REPO_FORMAT, which is the only option really used in code.
This is backwards compatible change: users are still free to define as many helper variables as they want, but the defaults are no longer misleading people to change only the helpers without having any effect.
JIRA: PDC-2451
> Document options for Dist-Git urls

- pdc/apps/common/tests.py
- pdc/apps/common/viewsets.py
- pdc/apps/module/tests.py
- pdc/apps/package/serializers.py
- pdc/apps/package/tests.py
- pdc/apps/utils/middleware.py
When it creates a new object in database, it should publish a message about it.
Both use cases are updated to test that the message was actually sent.
JIRA: PDC-2603
> Send messages from RPMRelated field

- pdc/apps/module/filters.py
- pdc/apps/module/tests.py
Filtering by
rest_api/v1/modules/?component=wayland/master&component=glibc/f28
shall show all components containing either:
- an RPM with **name "wayland" and srpm_commit_branch "master"** or
- an RPM with **name "glibc" and srpm_commit_branch "f28"**.
JIRA: PDC-2254
---
Fixes #458
> Add filter for modules for RPM name and branch

- pdc/apps/compose/forms.py
- pdc/apps/release/forms.py
The `is_valid` method only returns a bool indicating success or failure, there are no exceptions. This can actually lead to a 500 error.
The error can be replicated with
curl -X HEAD https://pdc/compose/<pk>/images/<variant>/<arch>
with valid combination of compose pk, variant uid and arch.
> Fix form validation in web UI
